[package]
name = "serverless-dts-generator"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/KisaragiEffective/serverless-dts-generator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.2.1", features = ["derive"] }
serde = { version = "1.0.156", features = ["derive"] }
serde_yaml = "0.9.19"
strum = { version = "0.24.1", features = ["derive"] }
